name = "Sam Apocalypse"
author = "Sam"
version = "1.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "951181cb5f653cd6efbf06390f58b79d56e3d3bdaace27f20f3af94dab261c03"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
