name = "Sam Apocalypse"
author = "Sam"
version = "1.7.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aade0de7be2a4abda436eb1c63d39539e55e16907769031e8ac5e3eca88ffe59"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
