name = "Sam Apocalypse"
author = "Sam"
version = "1.2.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8ae9212edd45f8c413a5706f7f54b85f55d910ad7a887e68df463544bbb7e8b"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
