name = "Sam Apocalypse"
author = "Sam"
version = "1.5.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d0a87decc40a12322b78beaeef9e2ea56133748b4487e72cab26d3818eee559"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
