name = "Sam Apocalypse"
author = "Sam"
version = "1.9.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6073b5141e81839bdf44044f0a9f37ca6f76acc963730efe7aa601d90f06d790"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
