name = "Sam Apocalypse"
author = "Sam"
version = "1.2.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b811f2ed5efa360bcd12f257e0a199dca500ba1706519b3f939bcc6de5c38c9"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
