name = "Sam Apocalypse"
author = "Sam"
version = "1.3.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a702b962e5e054057fe3a05b2d72cd3ab03c4103e04837694ec92635630e2285"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
