name = "Sam Apocalypse"
author = "Sam"
version = "1.6.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "663e7409b103ca2d3ccaf7576c585916ac8f893eb09b0795c4e57f18312c7c19"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
