name = "Sam Apocalypse"
author = "Sam"
version = "1.9.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cef111e424abda029675de3f8e1bc76e33c4e82ff0357afb30601ad8dd657414"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
