name = "Sam Apocalypse"
author = "Sam"
version = "1.9.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b1860e6096ea13e6a28cd49df95597172004bd46698b0030bea2b0e0f954531"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
