name = "Sam Apocalypse"
author = "Sam"
version = "1.9.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dad4de51fd2e6b04b119ce7ae4660e6ae22982c3a33b5692a6f464ebc22ec06"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
