name = "Sam Apocalypse"
author = "Sam"
version = "1.3.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8682fd5395583cf7c7e4eff5082e5de020fb022e82e0ef2f6c844619c0c91eb5"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
