name = "Sam Apocalypse"
author = "Sam"
version = "1.5.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f93f987360c5e364f9858ec022546a7d90343ebb5690048fda73a5c4be68978"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
