name = "Sam Apocalypse"
author = "Sam"
version = "1.5.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fa59ebe6ae101b7a2f5df33d1221fa77fd31c3a071296a4ad37badf1fb28dae"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
