name = "Sam Apocalypse"
author = "Sam"
version = "1.5.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b47a391c606e458952caef7cf5d14c58507dfc808b81d4d88bf1e53e57a8f37"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
