name = "Sam Apocalypse"
author = "Sam"
version = "1.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c99739c5cffb2fd0b97d86bdc4b16ed906a662f6b2eef289a0ce4295a000f1b"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
