name = "Sam Apocalypse"
author = "Sam"
version = "1.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4142032bbe4e32f6d2f197b85f1aefa9606a71e5a3af7c6ea0856a667a7e5e11"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
