name = "Sam Apocalypse"
author = "Sam"
version = "1.9.9c"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89a9c02ffc17c57da6030c4a865aa27492f6dd43d0c6a6840e36e96182de156d"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
