name = "Sam Apocalypse"
author = "Sam"
version = "1.9.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28299fc6ac9e4c1f5e321b13947568023fdce92e82293ef4c3ea32d709e6173e"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
