name = "Sam Apocalypse"
author = "Sam"
version = "1.7.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b3d86b0418dbe872e238f764e9d76a918a8d184e835d726016c1cb74f79c84a"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
