name = "Sam Apocalypse"
author = "Sam"
version = "1.2.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4472c0e999235aea3aad5a585444c8e2816acabb46167a7d71bb5924d860c077"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
