name = "Sam Apocalypse"
author = "Sam"
version = "1.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfa334c1bc04db8b49b13655610778bf21112218b78427e72df54485d97a450c"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
