name = "Sam Apocalypse"
author = "Sam"
version = "1.2.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93c35cc38ea1e00a545915e769af2882617bd2609e2e3e58b1a67167f2340e38"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
