name = "Sam Apocalypse"
author = "Sam"
version = "1.3.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b78b3f0838febe8d99d33f532038245e9c998b53db57711f8ac10c1512c84fb"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
