name = "Sam Apocalypse"
author = "Sam"
version = "1.2.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "848d74a45a124c3b66f80b313bb31dceeb4c91276916c42bad0d54b9313d0d66"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
