name = "Sam Apocalypse"
author = "Sam"
version = "1.2.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94ee23d98679d68d1ead5ded8cdc22f36684af61e086b4b444ca4ca2d7eea73b"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
