name = "Sam Apocalypse"
author = "Sam"
version = "1.2.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85ed37717233346129ea10142f4c90239dc33c543eedae33d32a12a2ed9f0f81"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
