name = "Sam Apocalypse"
author = "Sam"
version = "1.5.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "377c5035779f453975eee35e2d5e7435ebc06e02c03cf36cd2771f7422d22f5d"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
