name = "Sam Apocalypse"
author = "Sam"
version = "1.5.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc1fbc8ebe42107536833ae61c35b261c4031aa7e83f974b51903066c7185e63"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
