name = "Sam Apocalypse"
author = "Sam"
version = "2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58f6b04540d9ff0612c8780973a827e46d104686b00d741e5fc88a69356a1802"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
