name = "Sam Apocalypse"
author = "Sam"
version = "1.2.9"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f5e474a49dee9518e20d337236d8a489e3a31d6f698d7524825548392a18fb0"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
