name = "Sam Apocalypse"
author = "Sam"
version = "1.9.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ff4f515551ff91cf7593be4d53262225d353586660a6008f9c30821b9a5a197"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
