name = "Sam Apocalypse"
author = "Sam"
version = "1.3.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f75281e2c06e3c908fa8fd1988d92cdeb49435387c8837b3587fc1e7e630489"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
