name = "Sam Apocalypse"
author = "Sam"
version = "1.3.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbfd7a76da9e201f791626c622e728c8da8b7de8449d22175d7cbb2079324e68"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
