name = "Sam Apocalypse"
author = "Sam"
version = "1.9.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50663aa52de3975ff9ef15f7ff4f6c3b9de17b3867edccc418e93f33601c1aed"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
