name = "Sam Apocalypse"
author = "Sam"
version = "1.2.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8abb633302a5e6acb2cf4d2659f9926ba76f5e9e7f23eb1fbe8b14351aef698b"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
