name = "Sam Apocalypse"
author = "Sam"
version = "1.2.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c263dafbb80e8328112d62b3a12faf8b13c40bcfc5b59c93edb52f6ca3db7a0"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
