name = "Sam Apocalypse"
author = "Sam"
version = "1.2.9"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5e9c43488ceb1ef7e4c9d7280bdb246433570c4cb3159cd6d218689cc7d93b3"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
