name = "Sam Apocalypse"
author = "Sam"
version = "1.2.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3319fc4d0d0b6afb6032dffd92744a7f398e2f31583449574a541469fd1ae63d"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
