name = "Sam Apocalypse"
author = "Sam"
version = "1.5.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38eccc6ddbf5cec3c1e0319a51bcba361f6ad6e5eeac4f1f28c3a5999e67be6e"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
