name = "Sam Apocalypse"
author = "Sam"
version = "1.3.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf6683e1ed36e50576c902bce35be8f20fbb4cba14d2cdd07048d174403d96c5"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
