name = "Sam Apocalypse"
author = "Sam"
version = "1.2.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7c4e746d56bc58b5379112a2be93cc51968b652a7faf5d60463e9e9408fefed"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
