name = "Sam Apocalypse"
author = "Sam"
version = "1.3.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5893af21c0683b1d3217f12c671c2376ac8a2b243c63824ee2bafe5ec5a7163"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"
