name = "Sam Apocalypse"
author = "Sam"
version = "1.8.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c10fc88b4f51bb40971efe1d3a04e2e857a38e054edbe793d9be4a687412bda5"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
