name = "Architectury API (Forge)"
filename = "architectury-1.26.42.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3577/751/architectury-1.26.42.jar"
hash-format = "murmur2"
hash = "4136033146"

[update]
[update.curseforge]
file-id = 3577751
project-id = 419699
