name = "Bad Mobs"
filename = "BadMobs-1.16.5-9.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/403/BadMobs-1.16.5-9.0.5.jar"
hash-format = "murmur2"
hash = "1170207388"

[update]
[update.curseforge]
file-id = 3591403
project-id = 233258
