name = "Biomes O' Plenty"
filename = "BiomesOPlenty-1.16.5-13.1.0.485-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/343/BiomesOPlenty-1.16.5-13.1.0.485-universal.jar"
hash-format = "murmur2"
hash = "1509098138"

[update]
[update.curseforge]
file-id = 3591343
project-id = 220318
