name = "Carry On"
filename = "carryon-1.16.5-1.15.5.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/466/carryon-1.16.5-1.15.5.22.jar"
hash-format = "murmur2"
hash = "1006165690"

[update]
[update.curseforge]
file-id = 3579466
project-id = 274259
