name = "CodeChicken Lib 1.8.+"
filename = "CodeChickenLib-1.16.5-4.0.5.438-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3553/742/CodeChickenLib-1.16.5-4.0.5.438-universal.jar"
hash-format = "murmur2"
hash = "412176464"

[update]
[update.curseforge]
file-id = 3553742
project-id = 242818
