name = "Collective (Forge)"
filename = "collective-1.16.5-3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3533/132/collective-1.16.5-3.0.jar"
hash-format = "murmur2"
hash = "821420570"

[update]
[update.curseforge]
file-id = 3533132
project-id = 342584
