name = "Configured"
filename = "configured-1.5.1-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/348/configured-1.5.1-1.16.5.jar"
hash-format = "murmur2"
hash = "3114506489"

[update]
[update.curseforge]
file-id = 3546348
project-id = 457570
