name = "ContentTweaker"
filename = "ContentTweaker-1.16-1.0.0.develop.33.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/842/ContentTweaker-1.16-1.0.0.develop.33.jar"
hash-format = "murmur2"
hash = "2459253575"

[update]
[update.curseforge]
file-id = 3587842
project-id = 237065
