name = "Corpse"
filename = "corpse-1.16.5-1.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3447/907/corpse-1.16.5-1.0.6.jar"
hash-format = "murmur2"
hash = "212884507"

[update]
[update.curseforge]
file-id = 3447907
project-id = 316582
