name = "Cosmetic Armor Reworked"
filename = "CosmeticArmorReworked-1.16.5-v4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3398/0/CosmeticArmorReworked-1.16.5-v4.jar"
hash-format = "murmur2"
hash = "1715933748"

[update]
[update.curseforge]
file-id = 3398000
project-id = 237307
