name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.2.484.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/768/CraftTweaker-1.16.5-7.1.2.484.jar"
hash-format = "murmur2"
hash = "3324463401"

[update]
[update.curseforge]
file-id = 3590768
project-id = 239197
