name = "Curios API (Forge)"
filename = "curios-forge-1.16.5-4.0.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3456/953/curios-forge-1.16.5-4.0.5.3.jar"
hash-format = "murmur2"
hash = "920080633"

[update]
[update.curseforge]
file-id = 3456953
project-id = 309927
