name = "Curios API (Forge)"
filename = "curios-forge-1.16.5-4.0.6.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3551/128/curios-forge-1.16.5-4.0.6.5.jar"
hash-format = "murmur2"
hash = "1944550150"

[update]
[update.curseforge]
file-id = 3551128
project-id = 309927
