name = "Desolation (Forge)"
filename = "Desolation 1.0.1 1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3586/569/Desolation 1.0.1 1.16.5.jar"
hash-format = "murmur2"
hash = "2960252982"

[update]
[update.curseforge]
file-id = 3586569
project-id = 445926
