name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-1.16.5-7.0.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3488/440/EnchantmentDescriptions-1.16.5-7.0.17.jar"
hash-format = "murmur2"
hash = "1038572397"

[update]
[update.curseforge]
file-id = 3488440
project-id = 250419
