name = "FastWorkbench"
filename = "FastWorkbench-1.16.5-4.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3566/919/FastWorkbench-1.16.5-4.6.1.jar"
hash-format = "murmur2"
hash = "1972748246"

[update]
[update.curseforge]
file-id = 3566919
project-id = 288885
