name = "FastWorkbench"
filename = "FastWorkbench-1.16.5-4.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3531/308/FastWorkbench-1.16.5-4.6.0.jar"
hash-format = "murmur2"
hash = "670920427"

[update]
[update.curseforge]
file-id = 3531308
project-id = 288885
