name = "FastFurnace"
filename = "FastFurnace-1.16.5-4.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3531/342/FastFurnace-1.16.5-4.5.0.jar"
hash-format = "murmur2"
hash = "4244348145"

[update]
[update.curseforge]
file-id = 3531342
project-id = 299540
