name = "First Join Message (Forge)"
filename = "firstjoinmessage_1.16.5-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3379/846/firstjoinmessage_1.16.5-1.3.jar"
hash-format = "murmur2"
hash = "2768763119"

[update]
[update.curseforge]
file-id = 3379846
project-id = 390733
