name = "FTB Quests (Forge)"
filename = "ftb-quests-forge-1605.3.6-build.76.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/814/ftb-quests-forge-1605.3.6-build.76.jar"
hash-format = "murmur2"
hash = "3819484465"

[update]
[update.curseforge]
file-id = 3575814
project-id = 289412
