name = "FTB Money (Forge)"
filename = "ftb-money-1605.1.3-build.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/11/ftb-money-1605.1.3-build.6.jar"
hash-format = "murmur2"
hash = "3908621614"

[update]
[update.curseforge]
file-id = 3543011
project-id = 306283
