name = "Iron Chests"
filename = "ironchest-1.16.5-11.2.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/538/ironchest-1.16.5-11.2.21.jar"
hash-format = "murmur2"
hash = "1762825494"

[update]
[update.curseforge]
file-id = 3543538
project-id = 228756
