name = "Item Stages"
filename = "ItemStages-Forge-1.16.5-3.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3482/955/ItemStages-Forge-1.16.5-3.0.9.jar"
hash-format = "murmur2"
hash = "3703214841"

[update]
[update.curseforge]
file-id = 3482955
project-id = 280316
