name = "JEITweaker"
filename = "JEITweaker-1.16.5-1.0.1.35.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3468/722/JEITweaker-1.16.5-1.0.1.35.jar"
hash-format = "murmur2"
hash = "134499280"

[update]
[update.curseforge]
file-id = 3468722
project-id = 368718
