name = "MCMT"
filename = "jmt_mcmt-1.16.5-0.22.87.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3457/863/jmt_mcmt-1.16.5-0.22.87.jar"
hash-format = "murmur2"
hash = "2665591212"

[update]
[update.curseforge]
file-id = 3457863
project-id = 401447
