name = "More Mounted Storages"
filename = "moremountedstorages-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3536/361/moremountedstorages-1.2.0.jar"
hash-format = "murmur2"
hash = "322045780"

[update]
[update.curseforge]
file-id = 3536361
project-id = 546782
