name = "ObserverLib"
filename = "observerlib-1.16.5-1.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3333/962/observerlib-1.16.5-1.5.3.jar"
hash-format = "murmur2"
hash = "2841987314"

[update]
[update.curseforge]
file-id = 3333962
project-id = 316833
