name = "Open Loader"
filename = "OpenLoader-1.16.5-9.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3199/872/OpenLoader-1.16.5-9.0.3.jar"
hash-format = "murmur2"
hash = "3065879367"

[update]
[update.curseforge]
file-id = 3199872
project-id = 354339
