name = "Pam's HarvestCraft 2 - Crops"
filename = "pamhc2crops-1.16.3-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3276/350/pamhc2crops-1.16.3-1.0.2.jar"
hash-format = "murmur2"
hash = "1637623446"

[update]
[update.curseforge]
file-id = 3276350
project-id = 361385
