name = "Pam's HarvestCraft 2 - Trees"
filename = "pamhc2trees-1.16.3-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3281/234/pamhc2trees-1.16.3-1.0.1.jar"
hash-format = "murmur2"
hash = "1117650679"

[update]
[update.curseforge]
file-id = 3281234
project-id = 365460
