name = "Pam's HarvestCraft 2 - Food Extended"
filename = "pamhc2foodextended-1.16.3-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3418/627/pamhc2foodextended-1.16.3-1.0.4.jar"
hash-format = "murmur2"
hash = "245866351"

[update]
[update.curseforge]
file-id = 3418627
project-id = 402231
