name = "Polymorph (Forge)"
filename = "polymorph-forge-1.16.5-0.38.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/712/polymorph-forge-1.16.5-0.38.jar"
hash-format = "murmur2"
hash = "1950552754"

[update]
[update.curseforge]
file-id = 3587712
project-id = 388800
