name = "ReAuth"
filename = "ReAuth-1.16-Forge-3.9.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3105/779/ReAuth-1.16-Forge-3.9.3.jar"
hash-format = "murmur2"
hash = "2323416152"

[update]
[update.curseforge]
file-id = 3105779
project-id = 237701
