name = "Security Craft"
filename = "%5B1.16.5%5D SecurityCraft v1.8.23.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3398/327/%5B1.16.5%5D SecurityCraft v1.8.23.jar"
hash-format = "murmur2"
hash = "4286357527"

[update]
[update.curseforge]
file-id = 3398327
project-id = 64760
