name = "Security Craft"
filename = "[1.16.5] SecurityCraft v1.9.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3577/166/[1.16.5] SecurityCraft v1.9.0.2.jar"
hash-format = "murmur2"
hash = "409390877"

[update]
[update.curseforge]
file-id = 3577166
project-id = 64760
