name = "Starter Kit (Forge)"
filename = "starterkit_1.16.5-3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3539/859/starterkit_1.16.5-3.1.jar"
hash-format = "murmur2"
hash = "2631300401"

[update]
[update.curseforge]
file-id = 3539859
project-id = 390717
