name = "Survive"
filename = "Survive-1.16.5-3.4.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3536/642/Survive-1.16.5-3.4.5.jar"
hash-format = "murmur2"
hash = "3894390753"

[update]
[update.curseforge]
file-id = 3536642
project-id = 367337
