name = "TenshiLib"
filename = "TenshiLib-1.16.3-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3067/125/TenshiLib-1.16.3-1.3.0.jar"
hash-format = "murmur2"
hash = "4132839479"

[update]
[update.curseforge]
file-id = 3067125
project-id = 312040
