name = "Villagers Leashed!"
filename = "villagersleashed-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3317/243/villagersleashed-1.16.5-1.2.0.jar"
hash-format = "murmur2"
hash = "4083777302"

[update]
[update.curseforge]
file-id = 3317243
project-id = 451201
