name = "Villagers Leashed!"
filename = "villagersleashed-1.16.5-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3317/243/villagersleashed-1.16.5-1.2.0.jar"
hash-format = "md5"
hash = "a103b182c5d6aa79956c8c20d33a1b2a"

[update]
[update.curseforge]
file-id = 3317243
project-id = 451201