name = "Villagers Leashed!"
filename = "villagersleashed-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3364/954/villagersleashed-1.0.0.jar"
hash-format = "murmur2"
hash = "1327377428"

[update]
[update.curseforge]
file-id = 3364954
project-id = 451201
