name = "Villagers Leashed!"
filename = "villagersleashed-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3354/481/villagersleashed-1.0.jar"
hash-format = "murmur2"
hash = "3458084224"

[update]
[update.curseforge]
file-id = 3354481
project-id = 451201
