name = "Xaero's World Map"
filename = "XaerosWorldMap_1.18.3_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3532/562/XaerosWorldMap_1.18.3_Forge_1.16.5.jar"
hash-format = "murmur2"
hash = "2572539432"

[update]
[update.curseforge]
file-id = 3532562
project-id = 317780
