name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.22.2_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3532/550/Xaeros_Minimap_21.22.2_Forge_1.16.5.jar"
hash-format = "murmur2"
hash = "296073945"

[update]
[update.curseforge]
file-id = 3532550
project-id = 263420
