name = "Xaero's World Map"
filename = "XaerosWorldMap_1.19.0_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3582/988/XaerosWorldMap_1.19.0_Forge_1.16.5.jar"
hash-format = "murmur2"
hash = "451156277"

[update]
[update.curseforge]
file-id = 3582988
project-id = 317780
