name = "Zombie Horse Spawn (Forge)"
filename = "zombiehorsespawn_1.16.5-3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/79/zombiehorsespawn_1.16.5-3.0.jar"
hash-format = "murmur2"
hash = "3250987391"

[update]
[update.curseforge]
file-id = 3414079
project-id = 345692
